default_language_version:
    python: python3.7.4

repos:
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        -   id: black
            args:
                - --line-length=100
                - --target-version=py36

    -   repo: https://github.com/myint/docformatter
        rev: master
        hooks:
        -   id: docformatter
            args:
                - -i
                - --make-summary-multi-line
                - --wrap-summaries=100
                - --wrap-descriptions=100
                - --pre-summary-newline

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.5.0
        hooks:
        -   id: end-of-file-fixer
        -   id: debug-statements
        -   id: requirements-txt-fixer
        -   id: mixed-line-ending

    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
        -   id: flake8
            args:
                - --max-line-length=100
                - --max-cognitive-complexity=15
                - --ignore=E203,E266,E501,W503
            additional_dependencies:
                - pep8-naming
                - flake8-builtins
                - flake8-comprehensions
                - flake8-bugbear
                - flake8-pytest-style
                - flake8-cognitive-complexity

    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v1.9.0
        hooks:
        -   id: reorder-python-imports
            args:
                - --py3-plus
                - --application-directories=.:biocdr

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.761
        hooks:
        -   id: mypy
            args:
                - --no-strict-optional
                - --ignore-missing-imports
